### ISSUE TITLE
Enhancement request: repeat the execution of `pre-exec-cmd` at set intervals

### ISSUE THREAD

**Issue by erikbor** [cryptode/cryptode#200]
@jjr840430 could you please implement a `pre-exec-cmd-interval` configuration/function.
The `pre-exec-cmd` should be run again at the defined interval in the `.json` file. The interval is defined in minutes.

E.g.:

`test.json`:
```
{
  "name": "test",
  "auto-connect": true,
  "pre-connect-exec": "/usr/local/bin/mfa-auth.sh test"
  "pre-connect-exec-interval": "60"
}
``` 

This will make `rvd` execute `/usr/local/bin/mfa-auth.sh test` every 60 minutes.

This entry should also be shown in `rvc status`. And please implement a check for the interval value, minimum is `1`, maximum is `24`. If this value is invalid then show `invalid` in `rvc status`.

**Comment by jjr840430** [comment]
@erikbor If `pre-connect-exec` was failed in future execution after connected, then what happened?
Should `rvc` disconnect VPN connection at this case?

**Comment by erikbor** [comment]
@jjr840430 that's actually a very good question :)

Since the `pre-connect-exec` is used for 2FA/MFA it would make sense to authenticate once and then when it fails to keep the VPN connection open because we cannot know why the  `pre-connect-exec` failed for the second or Nth time. It could be a network error, DNS issue, etc totally unrelated to the VPN itself. So in that case we want to keep the VPN connected.
However, `pre-connect-exec` could also fail because the VPN user account has been disabled and hence the `pre-connect-exec` 2FA/MFA will fail and thus the VPN needs to be disconnected too.

I think the latter would be the preferred action. But this needs to be documented clearly to prevent confusion amongst our users. @jjr840430 what do you think?

@ronaldtse what's your opinion about this issue?

**Comment by ronaldtse** [comment]
@erikbor @jjr840430 I think the following would make the most sense:

1. If we are DISCONNECTED, and pre-connect fails, we don't try to connect. We should make it clear in `rvc status` that pre-connect has failed and is therefore rvc is not connecting. If this is an auto-connect connection, we will continue to retry pre-connect (and subsequently connect if it succeeds), at the retry intervals.

2. If we are CONNECTED, and pre-connect fails, we don't disconnect. However we should show in `rvc status` that pre-connect has failed and if you disconnect now, RVC won't connect again until pre-connect returns a success.

@jjr840430 , could we also change the `"pre-connect-exec-interval": "60"` to take seconds instead of minutes? It allows better granularity this way 😉

**Comment by jjr840430** [comment]
@ronaldtse @erikbor This was implemented and merged to master. Can you try to check it? Thanks.
